INSERT INTO user (id, login, nom, prenom, password, role) 
VALUES (1, "jourdain", "jourdain", "erick", "$2a$10$CFleb5bK8a3.boLzTwe4aOsaPpulMmbj3ooAdTjY77Fx75XnKSj6S", "USER");
INSERT INTO form (id, titre, description, formulaire, version, createur, valide)
VALUES (1, "formulaire 1", null, "formulaire 1", 1, 1, 1);
INSERT INTO form (id, titre, description, formulaire, version, createur, valide)
VALUES (2, "formulaire 2", null, "formulaire 2", 1, 1, 1);
INSERT INTO form (id, titre, description, formulaire, version, createur, valide)
VALUES (3, "formulaire 3", null, "formulaire 3", 1, 1, 1);
INSERT INTO form (id, titre, description, formulaire, version, createur, valide)
VALUES (4, "formulaire 4", null, "formulaire 4", 1, 1, 1);
INSERT INTO form (id, titre, description, formulaire, version, createur, valide)
VALUES (5, "formulaire 5", null, "formulaire 5", 1, 1, 1);
INSERT INTO form (id, titre, description, formulaire, version, createur, valide)
VALUES (6, "formulaire 6", null, "formulaire 6", 1, 1, 1);
INSERT INTO form (id, titre, description, formulaire, version, createur, valide)
VALUES (7, "formulaire 7", null, "formulaire 7", 1, 1, 1);
INSERT INTO form (id, titre, description, formulaire, version, createur, valide)
VALUES (8, "formulaire 8", null, "formulaire 8", 1, 1, 1);
INSERT INTO form (id, titre, description, formulaire, version, createur, valide)
VALUES (9, "formulaire 9", null, "formulaire 9", 1, 1, 1);
INSERT INTO form (id, titre, description, formulaire, version, createur, valide)
VALUES (10, "formulaire 10", null, "formulaire 10", 1, 1, 1);
INSERT INTO form (id, titre, description, formulaire, version, createur, valide)
VALUES (11, "formulaire 11", null, "formulaire 11", 1, 1, 1);
INSERT INTO form (id, titre, description, formulaire, version, createur, valide)
VALUES (12, "formulaire 12", null, "formulaire 12", 1, 1, 1);
INSERT INTO form (id, titre, description, formulaire, version, createur, valide)
VALUES (13, "formulaire 13", null, "formulaire 13", 1, 1, 1);
INSERT INTO form (id, titre, description, formulaire, version, createur, valide)
VALUES (14, "formulaire 14", null, "formulaire 14", 1, 1, 1);
INSERT INTO form (id, titre, description, formulaire, version, createur, valide)
VALUES (15, "formulaire 15", null, "formulaire 15", 1, 1, 1);
INSERT INTO form (id, titre, description, formulaire, version, createur, valide)
VALUES (16, "formulaire 16", null, "formulaire 16", 1, 1, 1);
INSERT INTO form (id, titre, description, formulaire, version, createur, valide)
VALUES (17, "formulaire 17", null, "formulaire 17", 1, 1, 1);
INSERT INTO form (id, titre, description, formulaire, version, createur, valide)
VALUES (18, "formulaire 18", null, "formulaire 18", 1, 1, 1);
INSERT INTO form (id, titre, description, formulaire, version, createur, valide)
VALUES (19, "formulaire 19", null, "formulaire 19", 1, 1, 1);
INSERT INTo form (id, titre, description, formulaire, version, createur, valide)
VALUES (20, "formulaire 20", null, "formulaire 20", 1, 1, 1);
INSERT INTO form (id, titre, description, formulaire, version, createur, valide)
VALUES (21, "formulaire 21", null, "formulaire 21", 1, 1, 1);
INSERT INTO form (id, titre, description, formulaire, version, createur, valide)
VALUES (22, "formulaire 22", null, "formulaire 22", 1, 1, 1);
INSERT INTO form (id, titre, description, formulaire, version, createur, valide)
VALUES (23, "formulaire 23", null, "formulaire 23", 1, 1, 1);
INSERT INTO form (id, titre, description, formulaire, version, createur, valide)
VALUES (24, "formulaire 24", null, "formulaire 24", 1, 1, 1);
INSERT INTO form (id, titre, description, formulaire, version, createur, valide)
VALUES (25, "formulaire 25", null, "formulaire 25", 1, 1, 1);
