/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MainLayoutImport } from './routes/_mainLayout'
import { Route as MainLayoutSigninImport } from './routes/_mainLayout/signin'
import { Route as MainLayoutResetpwdImport } from './routes/_mainLayout/resetpwd'
import { Route as MainLayoutLoginImport } from './routes/_mainLayout/login'
import { Route as MainLayoutForbiddenImport } from './routes/_mainLayout/forbidden'
import { Route as MainLayoutCloseImport } from './routes/_mainLayout/close'
import { Route as MainLayoutAuthImport } from './routes/_mainLayout/_auth'
import { Route as MainLayoutAuthIndexImport } from './routes/_mainLayout/_auth/index'
import { Route as MainLayoutAuthFormulairesImport } from './routes/_mainLayout/_auth/formulaires'
import { Route as MainLayoutAuthAdminLayoutImport } from './routes/_mainLayout/_auth/_adminLayout'
import { Route as MainLayoutAuthOpportunitesIndexImport } from './routes/_mainLayout/_auth/opportunites/index'
import { Route as MainLayoutAuthOpportunitesNouvelleImport } from './routes/_mainLayout/_auth/opportunites/nouvelle'
import { Route as MainLayoutAuthOpportunitesUuidImport } from './routes/_mainLayout/_auth/opportunites/$uuid'
import { Route as MainLayoutAuthAdminLayoutAdminUtilisateursIndexImport } from './routes/_mainLayout/_auth/_adminLayout/admin/utilisateurs/index'
import { Route as MainLayoutAuthAdminLayoutAdminFormulairesIndexImport } from './routes/_mainLayout/_auth/_adminLayout/admin/formulaires/index'
import { Route as MainLayoutAuthAdminLayoutAdminUtilisateursUserSlugImport } from './routes/_mainLayout/_auth/_adminLayout/admin/utilisateurs/$userSlug'
import { Route as MainLayoutAuthAdminLayoutAdminFormulairesAjouterImport } from './routes/_mainLayout/_auth/_adminLayout/admin/formulaires/ajouter'
import { Route as MainLayoutAuthAdminLayoutAdminFormulairesFormSlugImport } from './routes/_mainLayout/_auth/_adminLayout/admin/formulaires/$formSlug'

// Create/Update Routes

const MainLayoutRoute = MainLayoutImport.update({
  id: '/_mainLayout',
  getParentRoute: () => rootRoute,
} as any)

const MainLayoutSigninRoute = MainLayoutSigninImport.update({
  path: '/signin',
  getParentRoute: () => MainLayoutRoute,
} as any)

const MainLayoutResetpwdRoute = MainLayoutResetpwdImport.update({
  path: '/resetpwd',
  getParentRoute: () => MainLayoutRoute,
} as any)

const MainLayoutLoginRoute = MainLayoutLoginImport.update({
  path: '/login',
  getParentRoute: () => MainLayoutRoute,
} as any)

const MainLayoutForbiddenRoute = MainLayoutForbiddenImport.update({
  path: '/forbidden',
  getParentRoute: () => MainLayoutRoute,
} as any)

const MainLayoutCloseRoute = MainLayoutCloseImport.update({
  path: '/close',
  getParentRoute: () => MainLayoutRoute,
} as any)

const MainLayoutAuthRoute = MainLayoutAuthImport.update({
  id: '/_auth',
  getParentRoute: () => MainLayoutRoute,
} as any)

const MainLayoutAuthIndexRoute = MainLayoutAuthIndexImport.update({
  path: '/',
  getParentRoute: () => MainLayoutAuthRoute,
} as any)

const MainLayoutAuthFormulairesRoute = MainLayoutAuthFormulairesImport.update({
  path: '/formulaires',
  getParentRoute: () => MainLayoutAuthRoute,
} as any)

const MainLayoutAuthAdminLayoutRoute = MainLayoutAuthAdminLayoutImport.update({
  id: '/_adminLayout',
  getParentRoute: () => MainLayoutAuthRoute,
} as any)

const MainLayoutAuthOpportunitesIndexRoute =
  MainLayoutAuthOpportunitesIndexImport.update({
    path: '/opportunites/',
    getParentRoute: () => MainLayoutAuthRoute,
  } as any)

const MainLayoutAuthOpportunitesNouvelleRoute =
  MainLayoutAuthOpportunitesNouvelleImport.update({
    path: '/opportunites/nouvelle',
    getParentRoute: () => MainLayoutAuthRoute,
  } as any)

const MainLayoutAuthOpportunitesUuidRoute =
  MainLayoutAuthOpportunitesUuidImport.update({
    path: '/opportunites/$uuid',
    getParentRoute: () => MainLayoutAuthRoute,
  } as any)

const MainLayoutAuthAdminLayoutAdminUtilisateursIndexRoute =
  MainLayoutAuthAdminLayoutAdminUtilisateursIndexImport.update({
    path: '/admin/utilisateurs/',
    getParentRoute: () => MainLayoutAuthAdminLayoutRoute,
  } as any)

const MainLayoutAuthAdminLayoutAdminFormulairesIndexRoute =
  MainLayoutAuthAdminLayoutAdminFormulairesIndexImport.update({
    path: '/admin/formulaires/',
    getParentRoute: () => MainLayoutAuthAdminLayoutRoute,
  } as any)

const MainLayoutAuthAdminLayoutAdminUtilisateursUserSlugRoute =
  MainLayoutAuthAdminLayoutAdminUtilisateursUserSlugImport.update({
    path: '/admin/utilisateurs/$userSlug',
    getParentRoute: () => MainLayoutAuthAdminLayoutRoute,
  } as any)

const MainLayoutAuthAdminLayoutAdminFormulairesAjouterRoute =
  MainLayoutAuthAdminLayoutAdminFormulairesAjouterImport.update({
    path: '/admin/formulaires/ajouter',
    getParentRoute: () => MainLayoutAuthAdminLayoutRoute,
  } as any)

const MainLayoutAuthAdminLayoutAdminFormulairesFormSlugRoute =
  MainLayoutAuthAdminLayoutAdminFormulairesFormSlugImport.update({
    path: '/admin/formulaires/$formSlug',
    getParentRoute: () => MainLayoutAuthAdminLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_mainLayout': {
      id: '/_mainLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_mainLayout/_auth': {
      id: '/_mainLayout/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainLayoutAuthImport
      parentRoute: typeof MainLayoutImport
    }
    '/_mainLayout/close': {
      id: '/_mainLayout/close'
      path: '/close'
      fullPath: '/close'
      preLoaderRoute: typeof MainLayoutCloseImport
      parentRoute: typeof MainLayoutImport
    }
    '/_mainLayout/forbidden': {
      id: '/_mainLayout/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof MainLayoutForbiddenImport
      parentRoute: typeof MainLayoutImport
    }
    '/_mainLayout/login': {
      id: '/_mainLayout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof MainLayoutLoginImport
      parentRoute: typeof MainLayoutImport
    }
    '/_mainLayout/resetpwd': {
      id: '/_mainLayout/resetpwd'
      path: '/resetpwd'
      fullPath: '/resetpwd'
      preLoaderRoute: typeof MainLayoutResetpwdImport
      parentRoute: typeof MainLayoutImport
    }
    '/_mainLayout/signin': {
      id: '/_mainLayout/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof MainLayoutSigninImport
      parentRoute: typeof MainLayoutImport
    }
    '/_mainLayout/_auth/_adminLayout': {
      id: '/_mainLayout/_auth/_adminLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainLayoutAuthAdminLayoutImport
      parentRoute: typeof MainLayoutAuthImport
    }
    '/_mainLayout/_auth/formulaires': {
      id: '/_mainLayout/_auth/formulaires'
      path: '/formulaires'
      fullPath: '/formulaires'
      preLoaderRoute: typeof MainLayoutAuthFormulairesImport
      parentRoute: typeof MainLayoutAuthImport
    }
    '/_mainLayout/_auth/': {
      id: '/_mainLayout/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainLayoutAuthIndexImport
      parentRoute: typeof MainLayoutAuthImport
    }
    '/_mainLayout/_auth/opportunites/$uuid': {
      id: '/_mainLayout/_auth/opportunites/$uuid'
      path: '/opportunites/$uuid'
      fullPath: '/opportunites/$uuid'
      preLoaderRoute: typeof MainLayoutAuthOpportunitesUuidImport
      parentRoute: typeof MainLayoutAuthImport
    }
    '/_mainLayout/_auth/opportunites/nouvelle': {
      id: '/_mainLayout/_auth/opportunites/nouvelle'
      path: '/opportunites/nouvelle'
      fullPath: '/opportunites/nouvelle'
      preLoaderRoute: typeof MainLayoutAuthOpportunitesNouvelleImport
      parentRoute: typeof MainLayoutAuthImport
    }
    '/_mainLayout/_auth/opportunites/': {
      id: '/_mainLayout/_auth/opportunites/'
      path: '/opportunites'
      fullPath: '/opportunites'
      preLoaderRoute: typeof MainLayoutAuthOpportunitesIndexImport
      parentRoute: typeof MainLayoutAuthImport
    }
    '/_mainLayout/_auth/_adminLayout/admin/formulaires/$formSlug': {
      id: '/_mainLayout/_auth/_adminLayout/admin/formulaires/$formSlug'
      path: '/admin/formulaires/$formSlug'
      fullPath: '/admin/formulaires/$formSlug'
      preLoaderRoute: typeof MainLayoutAuthAdminLayoutAdminFormulairesFormSlugImport
      parentRoute: typeof MainLayoutAuthAdminLayoutImport
    }
    '/_mainLayout/_auth/_adminLayout/admin/formulaires/ajouter': {
      id: '/_mainLayout/_auth/_adminLayout/admin/formulaires/ajouter'
      path: '/admin/formulaires/ajouter'
      fullPath: '/admin/formulaires/ajouter'
      preLoaderRoute: typeof MainLayoutAuthAdminLayoutAdminFormulairesAjouterImport
      parentRoute: typeof MainLayoutAuthAdminLayoutImport
    }
    '/_mainLayout/_auth/_adminLayout/admin/utilisateurs/$userSlug': {
      id: '/_mainLayout/_auth/_adminLayout/admin/utilisateurs/$userSlug'
      path: '/admin/utilisateurs/$userSlug'
      fullPath: '/admin/utilisateurs/$userSlug'
      preLoaderRoute: typeof MainLayoutAuthAdminLayoutAdminUtilisateursUserSlugImport
      parentRoute: typeof MainLayoutAuthAdminLayoutImport
    }
    '/_mainLayout/_auth/_adminLayout/admin/formulaires/': {
      id: '/_mainLayout/_auth/_adminLayout/admin/formulaires/'
      path: '/admin/formulaires'
      fullPath: '/admin/formulaires'
      preLoaderRoute: typeof MainLayoutAuthAdminLayoutAdminFormulairesIndexImport
      parentRoute: typeof MainLayoutAuthAdminLayoutImport
    }
    '/_mainLayout/_auth/_adminLayout/admin/utilisateurs/': {
      id: '/_mainLayout/_auth/_adminLayout/admin/utilisateurs/'
      path: '/admin/utilisateurs'
      fullPath: '/admin/utilisateurs'
      preLoaderRoute: typeof MainLayoutAuthAdminLayoutAdminUtilisateursIndexImport
      parentRoute: typeof MainLayoutAuthAdminLayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  MainLayoutRoute: MainLayoutRoute.addChildren({
    MainLayoutAuthRoute: MainLayoutAuthRoute.addChildren({
      MainLayoutAuthAdminLayoutRoute:
        MainLayoutAuthAdminLayoutRoute.addChildren({
          MainLayoutAuthAdminLayoutAdminFormulairesFormSlugRoute,
          MainLayoutAuthAdminLayoutAdminFormulairesAjouterRoute,
          MainLayoutAuthAdminLayoutAdminUtilisateursUserSlugRoute,
          MainLayoutAuthAdminLayoutAdminFormulairesIndexRoute,
          MainLayoutAuthAdminLayoutAdminUtilisateursIndexRoute,
        }),
      MainLayoutAuthFormulairesRoute,
      MainLayoutAuthIndexRoute,
      MainLayoutAuthOpportunitesUuidRoute,
      MainLayoutAuthOpportunitesNouvelleRoute,
      MainLayoutAuthOpportunitesIndexRoute,
    }),
    MainLayoutCloseRoute,
    MainLayoutForbiddenRoute,
    MainLayoutLoginRoute,
    MainLayoutResetpwdRoute,
    MainLayoutSigninRoute,
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_mainLayout"
      ]
    },
    "/_mainLayout": {
      "filePath": "_mainLayout.tsx",
      "children": [
        "/_mainLayout/_auth",
        "/_mainLayout/close",
        "/_mainLayout/forbidden",
        "/_mainLayout/login",
        "/_mainLayout/resetpwd",
        "/_mainLayout/signin"
      ]
    },
    "/_mainLayout/_auth": {
      "filePath": "_mainLayout/_auth.tsx",
      "parent": "/_mainLayout",
      "children": [
        "/_mainLayout/_auth/_adminLayout",
        "/_mainLayout/_auth/formulaires",
        "/_mainLayout/_auth/",
        "/_mainLayout/_auth/opportunites/$uuid",
        "/_mainLayout/_auth/opportunites/nouvelle",
        "/_mainLayout/_auth/opportunites/"
      ]
    },
    "/_mainLayout/close": {
      "filePath": "_mainLayout/close.tsx",
      "parent": "/_mainLayout"
    },
    "/_mainLayout/forbidden": {
      "filePath": "_mainLayout/forbidden.tsx",
      "parent": "/_mainLayout"
    },
    "/_mainLayout/login": {
      "filePath": "_mainLayout/login.tsx",
      "parent": "/_mainLayout"
    },
    "/_mainLayout/resetpwd": {
      "filePath": "_mainLayout/resetpwd.tsx",
      "parent": "/_mainLayout"
    },
    "/_mainLayout/signin": {
      "filePath": "_mainLayout/signin.tsx",
      "parent": "/_mainLayout"
    },
    "/_mainLayout/_auth/_adminLayout": {
      "filePath": "_mainLayout/_auth/_adminLayout.tsx",
      "parent": "/_mainLayout/_auth",
      "children": [
        "/_mainLayout/_auth/_adminLayout/admin/formulaires/$formSlug",
        "/_mainLayout/_auth/_adminLayout/admin/formulaires/ajouter",
        "/_mainLayout/_auth/_adminLayout/admin/utilisateurs/$userSlug",
        "/_mainLayout/_auth/_adminLayout/admin/formulaires/",
        "/_mainLayout/_auth/_adminLayout/admin/utilisateurs/"
      ]
    },
    "/_mainLayout/_auth/formulaires": {
      "filePath": "_mainLayout/_auth/formulaires.tsx",
      "parent": "/_mainLayout/_auth"
    },
    "/_mainLayout/_auth/": {
      "filePath": "_mainLayout/_auth/index.tsx",
      "parent": "/_mainLayout/_auth"
    },
    "/_mainLayout/_auth/opportunites/$uuid": {
      "filePath": "_mainLayout/_auth/opportunites/$uuid.tsx",
      "parent": "/_mainLayout/_auth"
    },
    "/_mainLayout/_auth/opportunites/nouvelle": {
      "filePath": "_mainLayout/_auth/opportunites/nouvelle.tsx",
      "parent": "/_mainLayout/_auth"
    },
    "/_mainLayout/_auth/opportunites/": {
      "filePath": "_mainLayout/_auth/opportunites/index.tsx",
      "parent": "/_mainLayout/_auth"
    },
    "/_mainLayout/_auth/_adminLayout/admin/formulaires/$formSlug": {
      "filePath": "_mainLayout/_auth/_adminLayout/admin/formulaires/$formSlug.tsx",
      "parent": "/_mainLayout/_auth/_adminLayout"
    },
    "/_mainLayout/_auth/_adminLayout/admin/formulaires/ajouter": {
      "filePath": "_mainLayout/_auth/_adminLayout/admin/formulaires/ajouter.tsx",
      "parent": "/_mainLayout/_auth/_adminLayout"
    },
    "/_mainLayout/_auth/_adminLayout/admin/utilisateurs/$userSlug": {
      "filePath": "_mainLayout/_auth/_adminLayout/admin/utilisateurs/$userSlug.tsx",
      "parent": "/_mainLayout/_auth/_adminLayout"
    },
    "/_mainLayout/_auth/_adminLayout/admin/formulaires/": {
      "filePath": "_mainLayout/_auth/_adminLayout/admin/formulaires/index.tsx",
      "parent": "/_mainLayout/_auth/_adminLayout"
    },
    "/_mainLayout/_auth/_adminLayout/admin/utilisateurs/": {
      "filePath": "_mainLayout/_auth/_adminLayout/admin/utilisateurs/index.tsx",
      "parent": "/_mainLayout/_auth/_adminLayout"
    }
  }
}
ROUTE_MANIFEST_END */
