/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SigninImport } from './routes/signin'
import { Route as ResetpwdImport } from './routes/resetpwd'
import { Route as LoginImport } from './routes/login'
import { Route as CloseImport } from './routes/close'
import { Route as MainLayoutImport } from './routes/_mainLayout'
import { Route as MainLayoutIndexImport } from './routes/_mainLayout/index'
import { Route as MainLayoutAdminLayoutImport } from './routes/_mainLayout/_adminLayout'
import { Route as MainLayoutAdminLayoutAdminUtilisateursIndexImport } from './routes/_mainLayout/_adminLayout/admin/utilisateurs/index'
import { Route as MainLayoutAdminLayoutAdminFormulairesIndexImport } from './routes/_mainLayout/_adminLayout/admin/formulaires/index'
import { Route as MainLayoutAdminLayoutAdminUtilisateursUserSlugImport } from './routes/_mainLayout/_adminLayout/admin/utilisateurs/$userSlug'
import { Route as MainLayoutAdminLayoutAdminFormulairesAjouterImport } from './routes/_mainLayout/_adminLayout/admin/formulaires/ajouter'
import { Route as MainLayoutAdminLayoutAdminFormulairesFormSlugImport } from './routes/_mainLayout/_adminLayout/admin/formulaires/$formSlug'

// Create/Update Routes

const SigninRoute = SigninImport.update({
  path: '/signin',
  getParentRoute: () => rootRoute,
} as any)

const ResetpwdRoute = ResetpwdImport.update({
  path: '/resetpwd',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const CloseRoute = CloseImport.update({
  path: '/close',
  getParentRoute: () => rootRoute,
} as any)

const MainLayoutRoute = MainLayoutImport.update({
  id: '/_mainLayout',
  getParentRoute: () => rootRoute,
} as any)

const MainLayoutIndexRoute = MainLayoutIndexImport.update({
  path: '/',
  getParentRoute: () => MainLayoutRoute,
} as any)

const MainLayoutAdminLayoutRoute = MainLayoutAdminLayoutImport.update({
  id: '/_adminLayout',
  getParentRoute: () => MainLayoutRoute,
} as any)

const MainLayoutAdminLayoutAdminUtilisateursIndexRoute =
  MainLayoutAdminLayoutAdminUtilisateursIndexImport.update({
    path: '/admin/utilisateurs/',
    getParentRoute: () => MainLayoutAdminLayoutRoute,
  } as any)

const MainLayoutAdminLayoutAdminFormulairesIndexRoute =
  MainLayoutAdminLayoutAdminFormulairesIndexImport.update({
    path: '/admin/formulaires/',
    getParentRoute: () => MainLayoutAdminLayoutRoute,
  } as any)

const MainLayoutAdminLayoutAdminUtilisateursUserSlugRoute =
  MainLayoutAdminLayoutAdminUtilisateursUserSlugImport.update({
    path: '/admin/utilisateurs/$userSlug',
    getParentRoute: () => MainLayoutAdminLayoutRoute,
  } as any)

const MainLayoutAdminLayoutAdminFormulairesAjouterRoute =
  MainLayoutAdminLayoutAdminFormulairesAjouterImport.update({
    path: '/admin/formulaires/ajouter',
    getParentRoute: () => MainLayoutAdminLayoutRoute,
  } as any)

const MainLayoutAdminLayoutAdminFormulairesFormSlugRoute =
  MainLayoutAdminLayoutAdminFormulairesFormSlugImport.update({
    path: '/admin/formulaires/$formSlug',
    getParentRoute: () => MainLayoutAdminLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_mainLayout': {
      id: '/_mainLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainLayoutImport
      parentRoute: typeof rootRoute
    }
    '/close': {
      id: '/close'
      path: '/close'
      fullPath: '/close'
      preLoaderRoute: typeof CloseImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/resetpwd': {
      id: '/resetpwd'
      path: '/resetpwd'
      fullPath: '/resetpwd'
      preLoaderRoute: typeof ResetpwdImport
      parentRoute: typeof rootRoute
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninImport
      parentRoute: typeof rootRoute
    }
    '/_mainLayout/_adminLayout': {
      id: '/_mainLayout/_adminLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainLayoutAdminLayoutImport
      parentRoute: typeof MainLayoutImport
    }
    '/_mainLayout/': {
      id: '/_mainLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainLayoutIndexImport
      parentRoute: typeof MainLayoutImport
    }
    '/_mainLayout/_adminLayout/admin/formulaires/$formSlug': {
      id: '/_mainLayout/_adminLayout/admin/formulaires/$formSlug'
      path: '/admin/formulaires/$formSlug'
      fullPath: '/admin/formulaires/$formSlug'
      preLoaderRoute: typeof MainLayoutAdminLayoutAdminFormulairesFormSlugImport
      parentRoute: typeof MainLayoutAdminLayoutImport
    }
    '/_mainLayout/_adminLayout/admin/formulaires/ajouter': {
      id: '/_mainLayout/_adminLayout/admin/formulaires/ajouter'
      path: '/admin/formulaires/ajouter'
      fullPath: '/admin/formulaires/ajouter'
      preLoaderRoute: typeof MainLayoutAdminLayoutAdminFormulairesAjouterImport
      parentRoute: typeof MainLayoutAdminLayoutImport
    }
    '/_mainLayout/_adminLayout/admin/utilisateurs/$userSlug': {
      id: '/_mainLayout/_adminLayout/admin/utilisateurs/$userSlug'
      path: '/admin/utilisateurs/$userSlug'
      fullPath: '/admin/utilisateurs/$userSlug'
      preLoaderRoute: typeof MainLayoutAdminLayoutAdminUtilisateursUserSlugImport
      parentRoute: typeof MainLayoutAdminLayoutImport
    }
    '/_mainLayout/_adminLayout/admin/formulaires/': {
      id: '/_mainLayout/_adminLayout/admin/formulaires/'
      path: '/admin/formulaires'
      fullPath: '/admin/formulaires'
      preLoaderRoute: typeof MainLayoutAdminLayoutAdminFormulairesIndexImport
      parentRoute: typeof MainLayoutAdminLayoutImport
    }
    '/_mainLayout/_adminLayout/admin/utilisateurs/': {
      id: '/_mainLayout/_adminLayout/admin/utilisateurs/'
      path: '/admin/utilisateurs'
      fullPath: '/admin/utilisateurs'
      preLoaderRoute: typeof MainLayoutAdminLayoutAdminUtilisateursIndexImport
      parentRoute: typeof MainLayoutAdminLayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  MainLayoutRoute: MainLayoutRoute.addChildren({
    MainLayoutAdminLayoutRoute: MainLayoutAdminLayoutRoute.addChildren({
      MainLayoutAdminLayoutAdminFormulairesFormSlugRoute,
      MainLayoutAdminLayoutAdminFormulairesAjouterRoute,
      MainLayoutAdminLayoutAdminUtilisateursUserSlugRoute,
      MainLayoutAdminLayoutAdminFormulairesIndexRoute,
      MainLayoutAdminLayoutAdminUtilisateursIndexRoute,
    }),
    MainLayoutIndexRoute,
  }),
  CloseRoute,
  LoginRoute,
  ResetpwdRoute,
  SigninRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_mainLayout",
        "/close",
        "/login",
        "/resetpwd",
        "/signin"
      ]
    },
    "/_mainLayout": {
      "filePath": "_mainLayout.tsx",
      "children": [
        "/_mainLayout/_adminLayout",
        "/_mainLayout/"
      ]
    },
    "/close": {
      "filePath": "close.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/resetpwd": {
      "filePath": "resetpwd.tsx"
    },
    "/signin": {
      "filePath": "signin.tsx"
    },
    "/_mainLayout/_adminLayout": {
      "filePath": "_mainLayout/_adminLayout.tsx",
      "parent": "/_mainLayout",
      "children": [
        "/_mainLayout/_adminLayout/admin/formulaires/$formSlug",
        "/_mainLayout/_adminLayout/admin/formulaires/ajouter",
        "/_mainLayout/_adminLayout/admin/utilisateurs/$userSlug",
        "/_mainLayout/_adminLayout/admin/formulaires/",
        "/_mainLayout/_adminLayout/admin/utilisateurs/"
      ]
    },
    "/_mainLayout/": {
      "filePath": "_mainLayout/index.tsx",
      "parent": "/_mainLayout"
    },
    "/_mainLayout/_adminLayout/admin/formulaires/$formSlug": {
      "filePath": "_mainLayout/_adminLayout/admin/formulaires/$formSlug.tsx",
      "parent": "/_mainLayout/_adminLayout"
    },
    "/_mainLayout/_adminLayout/admin/formulaires/ajouter": {
      "filePath": "_mainLayout/_adminLayout/admin/formulaires/ajouter.tsx",
      "parent": "/_mainLayout/_adminLayout"
    },
    "/_mainLayout/_adminLayout/admin/utilisateurs/$userSlug": {
      "filePath": "_mainLayout/_adminLayout/admin/utilisateurs/$userSlug.tsx",
      "parent": "/_mainLayout/_adminLayout"
    },
    "/_mainLayout/_adminLayout/admin/formulaires/": {
      "filePath": "_mainLayout/_adminLayout/admin/formulaires/index.tsx",
      "parent": "/_mainLayout/_adminLayout"
    },
    "/_mainLayout/_adminLayout/admin/utilisateurs/": {
      "filePath": "_mainLayout/_adminLayout/admin/utilisateurs/index.tsx",
      "parent": "/_mainLayout/_adminLayout"
    }
  }
}
ROUTE_MANIFEST_END */
