ALTER TABLE IF EXISTS `answer` DROP FOREIGN KEY IF EXISTS FKj6gdfexrxo63t9cbhfgln058a;

ALTER TABLE IF EXISTS `answer` DROP COLUMN IF EXISTS `devis`;

DROP TABLE IF EXISTS `devis`;

CREATE TABLE `devis`(
  id INTEGER NOT NULL AUTO_INCREMENT, reference TEXT NOT NULL, version INTEGER, created_at DATETIME DEFAULT CURRENT_DATE not null, primary key (id)
) engine = InnoDB;

ALTER TABLE IF EXISTS `answer` ADD COLUMN `devis` INTEGER;

ALTER TABLE IF EXISTS `answer`
ADD CONSTRAINT FKj6gdfexrxo63t9cbhfgln058a FOREIGN KEY (devis) REFERENCES devis (id);